README.md
added emojis for fun! and slight stylistic updates like uniform Sentence case.
=> docs(readme): light style update

framework/bee-py/poetry.lock, framework/bee-py/pyproject.toml
=> restrict python to versions 3.11 and 3.12

framework/bee-py/README.md
=> fix: Update bee-py README.md

bee-hive/agent_schema.json
part of #48 
Initial version of the agent schema
=> add agent definition json schema

bee-hive/agent_schema.json
Fix #48 
Add input, output attributes and requires.
=> update agent definition json schema

bee-hive/create_agents.py, bee-hive/run_workflow.py
Apply code checks and style
```bash
black .
ruff check .
```
=> clean: apply code styles and clean not used variables/imports

bee-hive/bee_hive/create_agents.py
This is what we can do for now.  WDYT
Fix: #47
=> add input and output as format in instructions

framework/bee-py/bee_agent/llms/llm.py
=> pass base_url when inferencing

bee-hive/bee_hive/__init__.py, bee-hive/bee_hive/agent.py, bee-hive/bee_hive/workflow.py
I've created a base of POC1 from the current main branch files.  This PR can be merged or just used for reference.
=> poc1 skelton

framework/bee-py/bee_agent/llms/llm.py
allow passing an api key to the LLM
e.g., 
```python
llm = LLM(
model="openai/gpt-4o-mini",
api_key=YOUR_API_KEY
)
```
=> support passing apikey

bee-hive/bee_hive/workflow.py
fix #110 
example of the workflow class and run method is 
```
def parse_yaml(file_path):
with open(file_path, "r") as file:
yaml_data = list(yaml.safe_load_all(file))
return yaml_data
agents_yaml = parse_yaml("agent.yaml")
workflow_yaml = parse_yaml("workflow.yaml")
try:
workflow = Workflow(agents_yaml, workflow_yaml[0])
except Exception as excep:
raise RuntimeError("Unable to create agents") from excep
workflow.run()
```
The yaml schema is the same as poc 0.
=> Update sequence workflow

bee-hive/bee_hive/agent.py, bee-hive/bee_hive/step.py, bee-hive/bee_hive/workflow.py
fix #39 
This is a proposed implementation of the **condition.**. 
There is a new object `step` that has `name`, `condition`, `agent` and `dependencies`. 
Here is an example yaml file.  The condition is a python code that generate `output` object that has `prompt` and `next` items.  The `prompt` is a text output for the next step.  The `next` is the name of the next step.
Step in the `spec.template.start` is executed first.  The next step is the `next` in the `output` of the step execution.  The 'end' in the `next` finish the execution.  **The python execution for the condition evaluation is not safe.  It may need to be replaced some other way**
```
kind: Workflow
metadata:
name: beehive-deployment
labels:
app: mas-example
spec:
strategy:
type: condition
output: nonal
template:
metadata: …
```
=> add condition

bee-hive/bee_hive/__init__.py, bee-hive/bee_hive/interface.py
Fixes #108 
The plan is that all communication between agents will be sent via Messages, so that we provided a structure to the input/output.
Feel free to suggest alternatives / updates
=> add message class

bee-hive/bee_hive/agent.py, bee-hive/bee_hive/bee_agent.py, bee-hive/bee_hive/workflow.py
* Refactors Agent class to provide a base class & a bee specific class
* Also fixes error in json
Refactored version of #125 just for bee agent
A further PR will add back the crew.ai runner, as well as using a type field to create the correct agent type
tested with sample from https://github.com/i-am-bee/bee-hive/pull/124
```
(.venv) ➜  bee_hive git:(issue119c) ✗ python ./test_jokeworkworkflow.py
🐝 Running expert...
🐝 Response from expert: Why did the IBM computer go on a diet? Because it wanted to lose some bytes!
in condition
Why did the IBM computer go on a diet? Because it wanted to lose some bytes!
{'prompt': 'Why did the IBM computer go on a diet? Because it wanted to lose some bytes!', 'next': 'colleague'}
🐝 Running colleague...
🐝 Response from colleague: Thought: The joke is …
```
=> feat(internal): Refactor to provide base Agent class & allow for alt. runtimes

test/schema/validator.py
Schema validator:
```
python validator.py "workflow or agent yaml file name" "agent or workflow schema json file name"
```
=> feat(bee-hive) add schema validator

bee-hive/bee_hive/workflow.py, bee-hive/tests/bee/workflow.yaml, bee-hive/tests/crewai/workflow.yaml
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
We redid the schema but didn't update the test
=> fix workflow test

bee-hive/Dockerfile, bee-hive/README.md, bee-hive/bee-hive.sh, bee-hive/entrypoint.sh, bee-hive/run_workflow.py
This is a proposal for runtime.
Here is the way to run bee-hive with podman.  The user provides 2 yaml files(agents and workflow) and necessary environment variables for the agents.
```
podman run -e BEE_API=http://192.168.86.45:4000 -e BEE_API_KEY=sk-proj-testkey --mount type=bind,src="yaml file directory", target=/data  bee-hive /data/agents.yaml /data/workflow.yaml 
```
The `bee-hive` image is built by
```
podman build -t bee-hive
```
in `bee-hive/bee-hive` directory.
* Run a local instance of the [Bee Stack](https://github.com/i-am-bee/bee-stack)
* Build bee-hive container image: `./bee-hive.sh build` in	bee-hive/bee-hive directory
* Prepare agent and workflow definition yaml files in the current directory (e.g. agent.yaml, workflow.yaml)
* Run workflow: `./bee-hive.sh run $PWD …
=> Image Container

tools/workflow_schema.json
=> fix typo in workflow schema

bee-hive/cli/beeAI.py, bee-hive/cli/cli.py, bee-hive/cli/commands.py
Closes issue #113 when merged
* Will connect to  along with other commands in issue #167
* Will backfill tests in issue #168
@psschwei give me a quick review and LGTM since this is similar to PR #165
=> added  command stub to match the others `run` and `deploy`

bee-hive/bee_hive/mock_agent.py, bee-hive/bee_hive/workflow.py
MockAgent is added for testing.
MockAgent is created instead of BeeAgent or CrewAI agent when "BEE_TEST" env variable is set like `export BEE_TEST=1`
=> Add MockAgent

bee-hive/bee_hive/workflow.py
Quick update.
REF: https://github.com/i-am-bee/bee-hive/pull/172#pullrequestreview-2593726622
=> BEE_TEST to DRY_RUN

bee-hive/api.py, bee-hive/bee-hive.sh, bee-hive/bee_hive/step.py
The new command line output (./bee-hive run ....) is like:
```
Running...
🐝 Running expert...
🐝 Response from expert: Why did the IBM computer go on a diet? Because it wanted to lose some bytes!
🐝 Running colleague...
🐝 Response from colleague: Can you give me a funnier joke about IBM?
🐝 Running expert...
🐝 Response from expert: Why did the IBM computer go to therapy? Because it had a little glitch in its code! Hope that one loaded properly!
🐝 Running colleague...
🐝 Response from colleague: I'm happy to help, but I don't have the ability to rate jokes as of now. However, I can try to understand the humor behind it. Let me think...
```
=> format output and clean up debug outputs

bee-hive/Dockerfile, bee-hive/api.py, bee-hive/bee-hive.html
The workflow can be run from a web interface.  For kubernetes deployment, point to the bee-hive svc `/static/bee-hive.html`
It shows:
results are shown like:
=> add simple html file

bee-hive/bee_hive/workflow.py, bee-hive/tests/bee/workflow.yaml, bee-hive/tests/crewai/workflow.yaml, bee-hive/tests/workflow/workflow.yaml, test/examples/condition_workflow.yaml, test/yamls/workflows/conditional_workflow.yaml, test/yamls/workflows/simple_workflow.yaml
Updates workflow yaml files for the workflow schema change.
=> adjust yaml files for workflow schema change

bee-hive/bee_hive/mock_agent.py, test/yamls/agents/simple_agent.yaml, test/yamls/workflows/simple_workflow.yaml
2 changes for testing
1. Fix bug in MockAgent.
2. make `test/yamls/agents/simple_agent.yaml` and `test/yamls/workflows/simple_workflow.yaml` consistent
=> fix mock agent and make simple yamls consistent

bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml, bee-hive-demos/demos/activity-planner.ai/workflow.yaml, bee-hive-demos/demos/summary.ai/workflow.yaml, bee-hive-demos/demos/weather-checker.ai/workflow.yaml, bee-hive/tests/bee/workflow.yaml, bee-hive/tests/crewai/workflow.yaml, bee-hive/tests/workflow/workflow.yaml, test/examples/condition_workflow.yaml, test/yamls/workflows/funnier_workflow.yaml
Updates workflows to specify the agent list in correct format (see issue for details)
This is based on the spec being definitive. 
tested: pytest, crewai workflow
Partially addresses: #178
=> fix(agents): Correct agents array in workflow files

maestro/demos/workflows/activity-planner.ai/workflow.md
I think it would be useful to mermaid diagrams for existing demos.
=> Adds activity planner workflow diagram

maestro/demos/workflows/summary.ai/test_yaml/README.md, maestro/demos/workflows/summary.ai/test_yaml/agents.yaml, maestro/demos/workflows/summary.ai/test_yaml/workflow.yaml
Refactored after maestro refactor. Demo using cli tools, and test agent workflows. Will continue to work and clean this up, but might be good to merge a skeleton version that works end to end for now with all the refactors resolved. LMK your opinion. Continues from #220 which i closed since it was easier to create a new branch and unstash my changes
=> Updated refactor for demos

maestro/demos/workflows/summary.ai/test_yaml/README.md, maestro/demos/workflows/summary.ai/test_yaml/agents.yaml
https://github.com/i-am-bee/beeai-labs/issues/228
=> fixes issue #228

.github/workflows/maestro_demo-tests.yaml, maestro/demos/workflows/activity-planner.ai/doctor.sh, maestro/demos/workflows/weather-checker.ai/test.sh
* does not call `run.sh` but `test.sh` instead which runs workflow as `--dry-run`
* `doctor.sh` only checks `maestro` CLI is there but more could do more in future
* need to call `run.sh` in future
fixes issue #116
=> Runs the `weather-checker.ai` demo in CI

.github/workflows/maestro_demo-tests.yaml, maestro/demos/workflows/summary.ai/test_yaml/doctor.sh, maestro/demos/workflows/summary.ai/test_yaml/run.sh, maestro/demos/workflows/summary.ai/test_yaml/test.sh
fixes #242
Added integration tests only for summary.ai, including maestro validation for agents, workflows. 
Added github action to run the demo validation using poetry. Need to fix for other demos, will address in a separate PR.
=> Add demo tests

maestro/cli/commands.py, maestro/deployments/api.py
This PR fixes issues in maestro run command and deployed web server.
=> wrap workflow.run with asyncio.run

maestro/src/step.py, maestro/src/workflow.py, maestro/tests/yamls/agents/loop_agent.yaml, maestro/tests/yamls/workflows/loop_workflow.yaml
Add loop support
Run example:
```
maestro run tests/yamls/agents/loop_agent.yaml tests/yamls/workflows/loop_workflow.yaml
```
Test PR will follow.
=> add loop support

maestro/src/mock_agent.py, maestro/tests/bee/agents.yaml, maestro/tests/crewai/agents.yaml, maestro/tests/workflow/test_loop.py, maestro/tests/workflow/test_parallel.py, maestro/tests/yamls/agents/dry_run_loop_agent.yaml, maestro/tests/yamls/agents/dry_run_paralle_agent.yaml, maestro/tests/yamls/agents/simple_agent.yaml
Fix #262 
This PR adds tests for the loop and parallel workflow.  
The instructions of MocAgent is used as a python expression and used to generate the response of the agent.
=> Add test of  loop and parallel

maestro/schemas/tool_schema.json
=> Add Tool schema

.github/workflows/maestro_demo-tests.yaml, maestro/src/agents/meta_agent/doctor.sh, maestro/src/agents/meta_agent/test.sh, maestro/tools/run-meta-agent.sh
fixed #278 
added a specific workflow check for entire meta-agent folder, and also added gh actions check.
=> Create meta agent tests

maestro/src/deploy.py
fix default of env argument for deploy
=> fix default of env argument for deploy

maestro/tests/yamls/agents/dry_run_paralle_agent.yaml
=> Shorten parallel test

maestro/schemas/workflow_schema.json, maestro/tests/yamls/workflows/simple_cron_many_steps_workflow.yaml, maestro/tests/yamls/workflows/simple_cron_workflow.yaml
This fixes one sub-task of issue #289 
Please review @akihikokuroda and merge if good. Let's plan other PRs for the other sub-tasks.
=> proposed schema for cron job events

maestro/deployments/Dockerfile, maestro/deployments/api.py, maestro/deployments/maestro.html, maestro/tests/examples/condition_agents.yaml
This adds 
1. workflow name at the top
2. add the clear output check box
3. make the output field scrollable
4. add prompt input field for the re-run.
The URL is changed to "/" in this PR.
=> Update the UI deployed

maestro/deployments/maestro.html
This changes the background color to white.
=> Set UI background to white

maestro/demos/workflows/meta-agents-weather.ai/agents.yaml, maestro/demos/workflows/meta-workflow-weather.ai/agents.yaml
fixe #291 
For the demo I had a few prompts that were working better so edited them.
I am wondering should I add the generated agents.yaml/workflow.yaml files that meta agent creates? Or keep it out
=> prompt adjustments 

maestro/cli/commands.py, maestro/cli/maestro.py, maestro/src/mermaid.py, maestro/src/workflow.py, maestro/tests/cli/test_commands.py, maestro/tests/workflow/test_mermaid.py
fixes parts of issue #307
CC: @psschwei
=> implements CLI mermaid command

maestro/deployments/Dockerfile, maestro/src/agents/bee_agent.py
Create agent with tools (weather and web_search) in this PR.
The selective tools implementation would be in a separate PR.
=> Create agent tools

maestro/deployments/Dockerfile, maestro/deployments/maestro.html
=> Add workflow and agent definition links in UI

maestro/deployments/api.py, maestro/deployments/maestro.html, maestro/src/mermaid.py
=> Add workflow diagram in UI

maestro/deployments/api.py, maestro/deployments/maestro.html
part 1 of #302 Adding streaming output
There are still issues:
=> Streaming output

maestro/cli/commands.py
Fix #320
The urls for the local install are fixed.  This PR changes to display the url.
=> Fix end of deploy url message

maestro/demos/workflows/activity-planner.ai/agents.yaml, maestro/demos/workflows/activity-planner.ai/workflow.yaml, maestro/src/mermaid.py
There were some issues in the activity-planner.ai demo agent and workflow yaml files.
=> Fix activity demo 

.github/workflows/maestro_check-mermaid.yaml, maestro/tools/check-mermaid.sh
Solves the CI sub-task of issue #297
=> CI workflow / job to run maestro mermaid command on all existing workflows

maestro/README.md
Just a few updates that stuck out to me coming back to reading this.
=> improve readability of maestro readme

.github/workflows/maestro_check-schemas.yaml, maestro/cli/commands.py, maestro/cli/maestro.py, maestro/tests/cli/test_commands.py
Should help with #307 and #304 
Also fix small typo in GH action for schemas.
=> fixes issue #327

maestro/src/mermaid.py, maestro/tests/workflow/test_mermaid.py, maestro/tests/yamls/workflows/conditional_case_workflow.yaml, maestro/tests/yamls/workflows/conditional_if_workflow.yaml, maestro/tests/yamls/workflows/funnier_workflow.yaml
Splitting support for `condition` in mermaid into:
When done this will complete `condition` subtask in issue #297
=> feature: add support for condition (case/do/default and if/then/else)

maestro/schemas/workflow_schema.json, maestro/src/mermaid.py, maestro/tests/workflow/test_mermaid.py, maestro/tests/yamls/workflows/conditional_case_workflow.yaml, maestro/tests/yamls/workflows/conditional_if_workflow.yaml, maestro/tests/yamls/workflows/conditional_workflow.yaml, maestro/tests/yamls/workflows/input_workflow.yaml, maestro/tests/yamls/workflows/parallel_workflow.yaml, maestro/tests/yamls/workflows/simple_cron_many_steps_workflow.yaml, maestro/tests/yamls/workflows/simple_cron_workflow.yaml, maestro/tests/yamls/workflows/simple_workflow.yaml
When merged this will address the `exception` subtask of issue #297 
Highlights of the changes:
* changed workflow schema so that `exception` is now an `object` with `name` and `agent` properties
* added code to `Mermaid` class to deal with exception for sequence diagram and flowchart
* added tests for both cases
* refactored `Mermaid` class to have helper methods for `condition` and `exception` to make code more readable
Example mermaid generated for this simple workflow:
```yaml
apiVersion: maestro/v1
kind: Workflow
metadata:
name: simple workflow
labels:
app: example2
spec:
template:
metadata:
name: maestro-deployment
labels:
app: example
use-case: test
agents:
- test1
- test2
- test3
- test4
prompt: This is a test input
exception:
name: step4
agent: test4
steps:
- name: step1
agent: …
```
=> feature: add global exception to Mermaid generation

maestro/src/agents/bee_agent.py, maestro/src/agents/crewai_agent.py, maestro/src/agents/mock_agent.py
Add a new line to `BeeAgent` output and other agents as well.
=> fixes issue #339

maestro/src/agents/mock_agent.py
=> fixes issues #337

maestro/demos/workflows/activity-planner.ai/agents.yaml, maestro/demos/workflows/activity-planner.ai/workflow.yaml
update activity planner to get more consistent results via CLI in preparation for demo
=> prompt updates

maestro/cli/streamlit_meta_agents_deploy.py, maestro/src/agents/meta_agent/agents.yaml
agent definintion missed `---` so workflow agent file was not being read properly.
Changed the location of workflow yaml to the correct place
=> Bug: workflow deployment not rendering

maestro/cli/streamlit_deploy.py
fix #372 
This pr also have fix to make the prompt input work
=> Fix streaming output

maestro/cli/streamlit_workflow_ui.py
This PR adds streaming output to meta-agents streamlit UI.
=> Add streaming output to meta agent UI

maestro/cli/streamlit_workflow_ui.py
fix #386 
The mermaid diagram must be drawn in a tab when the tab is displayed.  To make it, this PR add a "Show Dialog" button so that the tab is displayed when the diagram is drawn.
Please check if this is an acceptable solution.
=> Add show diagram button to fix issue 386

maestro/cli/streamlit_deploy.py
=> Fix reset button issue

maestro/cli/streamlit_workflow_ui.py
There are 2 changes in this PR.
1. Add `Reset` button to meta agent UI
2. Fix issue starting workflow without displaying the dialog.
=> Add Reset button to meta agent UI

maestro/cli/streamlit_deploy.py
=> refactor streamlit deploy

maestro/src/agents/beeai_local_agent.py
The local beeai agent was broken.  This fix the issue.
=> Fix local beeai agent error

.github/workflows/maestro_check-schemas.yaml, maestro/demos/workflows/activity-planner-crewai.ai/README.md, maestro/demos/workflows/activity-planner.ai/README.md, maestro/demos/workflows/meta-agents/README.md, maestro/demos/workflows/summary.ai/README.md, maestro/demos/workflows/weather-checker.ai/README.md, maestro/src/agents/meta_agent/README.md, maestro/tools/update_readme.sh
fixes #307 
added `update_readme.sh` script to automate the updates to mermaid graphs in readme. Also will run automatically whenver there is a change made to the demos folder, this will be triggered.
you can test it by using `./update_readme.sh`
=> add mermaid diagrams to each demo

maestro/demos/workflows/summary.ai/README.md, maestro/demos/workflows/summary.ai/agents.yaml, maestro/demos/workflows/summary.ai/workflow.yaml
since we are demoing the summary agents, i further updated the entire demo to be a bit more consistent. 
updated readme also
created 2 new agents that replacted the old ones:
one that retrieves abstract from the arxiv based on the fetched titles
one that generates summary based on the paper and abstract
=> updating summary agents

maestro/demos/agents/crewai/activity_planner/__init__.py, maestro/demos/agents/crewai/activity_planner/activity_planner.py, maestro/demos/workflows/activity-planner-crewai.ai/agents.yaml, maestro/demos/workflows/activity-planner-crewai.ai/workflow.yaml, maestro/src/agents/crewai_agent.py
This PR is a part of #384 
The crew.ai activity planner can be run by this now:
```
maestro run demos/workflows/activity-planner-crewai.ai/agents.yaml demos/workflows/activity-planner-crewai.ai/workflow.yam
```
=> Adjusts crew.ai activity planner demo

.github/workflows/maestro_check-mermaid.yaml, .github/workflows/maestro_check-schemas.yaml, .github/workflows/maestro_demo-tests.yaml, .github/workflows/maestro_deploy-tests.yaml, .github/workflows/maestro_run-tests.yaml, maestro/pyproject.toml, maestro/src/agents/crewai_agent.py, maestro/tests/agents/crewai_agent/test_crewai.py
This is workaround for the litellm dependency issue between beeai_framework and crewai
Crewai is required older version of the litellm.  It be updated to resolve this issue.
=> litellm dependency conflict issue workaround

maestro/README.md
#440 This is readme update for the dependency workaround.
=> README update for dependency workaround

maestro/cli/commands.py, maestro/cli/maestro.py
This helps issue #439
A new command 
```
maestro clean
```  
is added.  This cleans all streamlit processes.
=> add maestro clean command to clean up streamlit processes

maestro/pyproject.toml, maestro/src/agents/agent.py, maestro/src/agents/agent_factory.py, maestro/src/agents/openai_agent.py, maestro/tests/agents/openai_agent/agents.yaml, maestro/tests/agents/openai_agent/agents_ollama.yaml, maestro/tests/agents/openai_agent/workflow.yaml, maestro/tests/agents/openai_agent/workflow_ollama.yaml, maestro/tests/agents/test_agent.py, maestro/tests/agents/test_agent_factory.py
* Adds support for Open AI Agents
* Moves emoji support into Agent (discussed with @akihikokuroda )
* Enables use of Ollama via openAI agent sdk
This is a continuation of/supercedes #414 (no permission to push to branch cc: @maximilien )
Partially Implements: #432
=> feature: add first working OpenAI agent

maestro/tests/workflow/test_cron.py, maestro/tests/workflow/test_mermaid.py, maestro/tests/yamls/workflows/simple_cron_many_steps_workflow.yaml
This makes sure that cron workflows run successfully.
=> Add simple test for event flow

maestro/src/agents/agent.py, maestro/src/agents/beeai_agent.py, maestro/src/agents/crewai_agent.py, maestro/src/agents/openai_agent.py
=> Use print in agent class for consistent emoji

maestro/demos/README.md, maestro/pyproject.toml, maestro/src/agents/agent_factory.py, maestro/src/agents/custom_agent.py, maestro/src/agents/slack_agent.py, maestro/tests/yamls/agents/slack_agent.yaml, maestro/tests/yamls/workflows/slack_workflow.yaml
Add the framework for the custom tool that can be used in the maestro workflow step.  Slack message posting tool is added as an example, too.
=> add custom agent support

maestro/README.md, maestro/demos/workflows/activity-planner-crewai.ai/README.md, maestro/demos/workflows/summary.ai/README.md, maestro/demos/workflows/weather-checker.ai/README.md
brief update to readme with instructions on starting from venv + what to install
also added new features like deploying to streamlit, auto updating mermaid in readme, etc
=> documentation: Readme updates

maestro/demos/workflows/summary.ai/agents.yaml
Generate summary agent was not performing consistently, adding more specified instructions to help output.
=> demo update: more consistent prompt

maestro/docs/README_openai.md
Fixes typos in readme as pointed out by @akihikokuroda in #453 after merge (thanks)
=> OpenAI - README typos

maestro/demos/workflows/summary.ai/agents.yaml
New updates w more generalized instructions to allow agents to pull from differerent categories in arXiv.
Format updates to output to make it more readable in the summary.
=> enhancement: generalize prompt

demos/workflows/summary.ai/README.md, demos/workflows/summary.ai/agents.yaml, demos/workflows/summary.ai/workflow.yaml
fixes #465
previously input prompt was something like this: function_name(param). now, added support via intial agent that can take in the english description to generate and output the correct function call
=> enhancement: added nlp agent for summary 

.github/workflows/maestro_demo-tests.yaml, .github/workflows/maestro_run-tests.yaml
Ensured setup for each run is the same as local virtual env by following the `setup_maestro` script
=> enhancement: update actions file w setup

src/agents/slack_agent.py
No other depedencies/occurrences yet, so simple renaming
=> typo: function name in slack agent

src/step.py, src/utils.py, src/workflow.py, tests/workflow/test_loop.py, tests/workflow/test_parallel.py, tests/yamls/agents/dry_run_loop_list_agent.yaml, tests/yamls/agents/dry_run_paralle_list_agent.yaml
=> enhancement: improve parallel and loop

src/agents/scoring_agent.py
Currently the litellm default model is set to openai, which doesn't work unless we have an openai key. This is causing issues when opik calls evaluation as it requires LLM calling.
Switching the backend to be ollama which works.
=> bug: scoring agent default model

src/agents/code_agent.py
Small typo fix
`Exception rxecuting code` should be `Exception executing code`
=> typo fix in the new code agent

docs/USER_GUIDE.md
Related to #496 
This is initial drop of the USER_GUIDE
There are still a lot to be added.
=> User guide

cli/commands.py, demos/workflows/weather-checker.ai/agents.yaml
values of metadata.labels must be sanitized to be in kubernates CR.
Add create-cr command error messages.
=> bug: values of metadata.labels must be sanitized

demos/workflows/portfolio/README.md, demos/workflows/portfolio/agent.yaml, demos/workflows/portfolio/workflow.yaml
The call to the quantum function is mocked now.  This is still very simple and works with only stocks now.
=> feature: add quantum portfolio optimizer workflow

demos/workflows/qaoa/README.md, demos/workflows/qaoa/agents.yaml, demos/workflows/qaoa/functions/qaoa/qaoa.py, demos/workflows/qaoa/scripts/upload_function.py, demos/workflows/qaoa/workflow.yaml
This is a start to running a QAOA workflow via Maestro.
Some parts are mocked (it is not clear how to pass input / output between agents), and it is untested (as there's a previously-identified issue with maestro+qiskit on linux).
=> demo: Qaoa workflow

tools/run-demos.sh
=> bug: skip slack agent

demos/workflows/portfolio/agents.yaml
Fix some issues in the portfolio code agent
=> Fix issues found with the real Quantum Portfolio Optimizer function 

demos/workflows/portfolio/README.md, demos/workflows/portfolio/agents.yaml
The doc for the quantum portfolio optimizer has wrong function name.  I forgot to update it in the last RP.
=> Fix wrong function name of portfolio optimizer

src/maestro/agents/agent.py, src/maestro/workflow.py, tests/agents/test_save_restore.py, tests/yamls/agents/beeai_agent.yaml, tests/yamls/agents/openai_agent.yaml
Add additional code to handle agent that can not be serialized by pickle.
fix #548
=> bug: fix save_agent

docs/USER_GUIDE.md, pyproject.toml, src/maestro/cli/commands.py, src/maestro/cli/fastapi_serve.py, src/maestro/cli/run_maestro.py, tests/integration/serve/test_serve_integration.py, tests/yamls/agents/serve_test_agent.yaml
Adds a `maestro serve` command to expose agents via an HTTP endpoint
=> feature: serve agent

schemas/tool_schema.json, tests/yamls/tools/simple_tools.yaml, tools/check-schemas.sh
This a part of #273
There are 3 changes in this PR.
1. enable tool yamls test in CI
2. add one sample tool yaml for testing
3. update tool schema (embedding jsonschema json string instead of yaml format schema definition"
=> chore: enable tool yaml validation in ci

tests/yamls/tools/duckduckgo_tools.yaml, tests/yamls/tools/openmeteo_tools.yaml, tests/yamls/tools/python_tools.yaml, tests/yamls/tools/simple_tools.yaml, tests/yamls/tools/wikipedia_tools.py
This is a part of #273 
Adding some BeeAI tool yamls
=> feature: add some beeai tool yamls

.release_names.md, pyproject.toml
Need to update pyproject minor so that its not the same as our latest release
=> chore: Update pyrpoject

.github/workflows/maestro_release.yaml, .release_names.md, tools/bump_version.py
followup to release automation:
- automatically sync top level readme version with current release version
- update pyproject.toml, incrementing the minor by 1 automatically
you can look at the test pr and actions report on my fork additionally to look at logs
fixes #593
=> enhacement: bump version automatically

operator/Dockerfile-engine, operator/entrypoint_api.sh, pyproject.toml, src/maestro/agents/agent.py, src/maestro/agents/agent_factory.py, src/maestro/agents/dspy_agent.py, tests/workflow/test_dspy_agent.py, tests/yamls/agents/dspy_agent.yaml, tests/yamls/workflows/dspy_workflow.yaml
fix #580 
Adding DSPy agent support
=> feature: DSPy Agent

src/maestro/agents/crewai_agent.py
=> chore: correct crewai dependency warning message

.github/workflows/maestro_operator-test.yaml, .github/workflows/maestro_release.yaml, .github/workflows/maestro_test-workflow.yaml
Followup to #632
Fixes the CI failure and other cleanup
=> chore: cleanup ci after demo move

src/maestro/agents/remote_agent.py
Fixes #633 
currently remote agent allows an agent to call a given API URL with a prompt. This is potentially useful for 3rd party agent workflows like langflow, but the current implementation hard-codes the request data object and response object.
The request data is `{"prompt": prompt}` and the response expects a json object with a `response` key. This is not very useful since not all agent api's don't use that data and response format.
This updates the spec to accept `request_template` and `response_template` to determine the json data object sent in the request and where to find the answer in the response object respectively.
An example agent yaml for a langflow api would look like:
```yaml
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
name: langflow
spec:
framework: remote
url: …
```
=> enhancement: make request data and response object configurable in RemoteAgent

README.md, src/maestro/cli/fastapi_serve.py, src/maestro/workflow.py, tests/integration/serve/test_streaming.py
fixes #682 enables the streaming of answers inside of maestro serve, this allows us to display the process inside of builder
=> feature: enable workflow streaming in api

.github/workflows/maestro_mcp_tool_test.yaml, docs/USER_GUIDE.md, operator/Dockerfile-engine, src/maestro/agents/beeai_agent.py, src/maestro/agents/dspy_agent.py, src/maestro/agents/openai_agent.py, src/maestro/agents/openai_mcp.py, src/maestro/tool_utils.py, tests/utils/responses.yml, tests/yamls/agents/beeai_mcp_agent.yaml, tests/yamls/agents/openai_mcp_agent.yaml, tests/yamls/workflows/beeai_mcp_workflow.yaml, tests/yamls/workflows/openai_mcp_workflow.yaml
Add MCP tool support utilities and DSPy agent change as the first example of the utility usage. 
ref #659
=> chore: Agent MCP tool support utilities 

Dockerfile, tools/buildimg.sh
Add a comment at top of the Dockerfile
Fix: #672
=> add comment in Dockerfile

src/maestro/cli/fastapi_serve.py
=> bug: recreate openai and dspy agents on restore in serve

.github/workflows/maestro_create_tool-test.yaml, .github/workflows/maestro_mcp_tool_test.yaml
fix #704 
fix maestro_mcp_tool_test.yaml and maestro_create_tool-test.yaml
=> bug: CI fix

docs/PRESENTATION.md, docs/presentation_script.md
=> feature: Maestro Introduction Presentation

CONTRIBUTING.md
=> update contributing steps

docs/PRESENTATION.md, docs/README_openai.md, docs/USER_GUIDE.md, src/maestro/__init__.py, src/maestro/agents/agent_factory.py, src/maestro/agents/beeai_agent.py, src/maestro/agents/meta_agent/agents.yaml, src/maestro/schemas/agent_schema.json, src/maestro/workflow.py, tests/yamls/agents/beeai_agent.yaml, tests/yamls/agents/code_exception_agent.yaml, tests/yamls/agents/dry_run_inputs_agent.yaml, tests/yamls/agents/funnier_agents.yaml, tests/yamls/agents/multi_agents.yaml, tests/yamls/agents/multi_agents_crew2.yaml, tests/yamls/agents/multi_agents_parallel.yaml, tests/yamls/agents/simple_agent.yaml, tests/yamls/agents/simple_remote_agents.yaml, tests/yamls/agents/simple_wow_agents.yaml
https://github.com/AI4quantum/maestro/issues/745
=> fix: deprecate beeai local only

src/maestro/cli/commands.py
Improve error message for the error of workflow yaml file in run command.
fix #743
=> enhance: improve workfile error handling
