AI4quantum/maestro

examples/bee-hive/weather-checker/README.md

The current weather checker app is under examples/bee-hive/weather-checker. My assumption is that the instructions placed here should work when the current working directory is this one.
As such the readme instructions for copying the .env file & installing dependencies are incorrect, as the top level directories being referring to are one level further up the tree.

Correct README for weather checker- adjust relative paths for file copies

---

tools/workflow_schema.json

Fixes the schema to use spaces (not tabs)
I was getting visual layout issues with the schema in vscode.
For example
This fix replaces with standard spaces

fix(internal): fix schema format (spaces/tabs) 

---

bee-hive/Dockerfile
bee-hive/README.md
bee-hive/api.py
bee-hive/bee-hive.sh
bee-hive/bee-hive.yaml
bee-hive/entrypoint_api.sh

This PR makes Bee-hive deployable and accessible in kubernetes.
A small API is added bee-hive image.  It accepts request with 2 yaml files and runs workflow.
This PR has kubernetes deployment and service (it's using a NodePort right now) yaml files.  The can be deployed with the kubectl.  The bee-hive with container runtime is also adjusted to use the API instead of mounting the local file system.  
The bee-hive.sh has 4 commands (the first argument)
* build: build container image
* deploy: deploy bee-hive in container service
* deploy-k: deploy bee-hive in kubernetes
* run: run the work flow in the environment
* Prepare required environments
* Run a local instance of the [Bee Stack](https://github.com/i-am-bee/bee-stack)
* `curl` is required for `run` command
* for Kubernetes, `kubectl` …

bee-hive in kubernetes

---

bee-hive/bee_hive/__init__.py
bee-hive/cli/beeAI.py
bee-hive/cli/cli.py
bee-hive/cli/commands.py
bee-hive/cli/common.py
bee-hive/pyproject.toml

- Enables projects to specify a dependency on the bee project and run 'beeAI' directly
**Detail**:
- Correct scope of some imports to work portably when picked up as a dependency (ie cli.XX)
- added script definition to poetry config (poetry will automatically create shell script)
- minor refactor to beeAI.py to move code to callable function (didn't work directly in main)
**Example**
In a new project which uses bee-hive, we can simply add bee-hive as a dependency:
```
[tool.poetry.dependencies]
python = ">= 3.11, < 3.13"
bee_hive = { git = "ssh://git@github.com/planetf1/bee-hive", subdirectory="bee-hive", branch="dev" }
```
Then in this new project, the following command works after a `poetry install`
```
(.venv) ➜  bee-hive git:(dev) beeAI validate file1 file2
validate file1 with schema …
```

fix(cli): Package cli for execution in dependent projects

---

bee-hive/cli/cli.py

- Fixes an issue with 'create' command not working when running via a dependency
Now works ie:
```
(bee-hive-demos-py3.12) ➜  src git:(dev/jonesn/activitymerge) poetry update
Updating dependencies
Resolving dependencies... (39.6s)
Package operations: 0 installs, 1 update, 0 removals
- Updating bee-hive (0.1.0 ebf3620 -> 0.1.0 637206f)
Writing lock file
(bee-hive-demos-py3.12) ➜  src git:(dev/jonesn/activitymerge) beeAI create agents.yaml                               
create: agents.yaml: OK.
```
Fixes #176

fix(cli): import additional commands

---

.github/workflows/tests.yaml
bee-hive-demos/agents/crewai/activity_planner/README.md
bee-hive-demos/agents/crewai/activity_planner/activity_planner.py
bee-hive-demos/demos/activity-planner-crewai.ai/README.md
bee-hive-demos/demos/activity-planner-crewai.ai/run.py
bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml
bee-hive/tests/bee/test_bee.py
bee-hive/tests/crewai/test_crewai.py
bee-hive/tests/workflow/test_sequence.py
pyproject.toml
test/examples/test_condition.py

This update consolidates dependencies to a SINGLE pyproject.toml at the TOP LEVEL
This is a short-term fix to address needs for iteration 1
**Details**
- merges changes from bee-hive-demos's pyproject.toml into single pyproject.toml
- moves to top level (relative paths not permitted in project section, and demos now moved to `bee-hive-demos`)
- module locations updated accordingly
- fixed tests to run from top level. Since they are sometimes run locally, this was done by changing `a/b/c/agents.yaml` to `os.path.join(os.path.dirname(__file__),"agents.yaml")` which should be portable, as it looks for the file in the same directory as the test code.
- fixed crewAI agent (standalone)
- fixed (temporary) crewAI demo workflow
- added simple READMEs for crewAI agent & example app
- corrected …

unify organization structure of demos

---

bee-hive-demos/demos/activity-planner-crewai.ai/run.py
bee-hive-demos/demos/activity-planner.ai/src/run.py
bee-hive/bee_hive/__init__.py
bee-hive/bee_hive/agent_factory.py
bee-hive/bee_hive/bee_agent.py
bee-hive/bee_hive/crewai_agent.py
bee-hive/bee_hive/mock_agent.py
bee-hive/bee_hive/step.py
bee-hive/bee_hive/workflow.py
bee-hive/cli/beeAI.py
bee-hive/cli/cli.py
bee-hive/cli/commands.py
bee-hive/run_workflow.py
bee-hive/tests/__init__.py
bee-hive/tests/bee/__init__.py
bee-hive/tests/bee/test_bee.py
bee-hive/tests/crewai/__init__.py
bee-hive/tests/crewai/crew_dummy.py
bee-hive/tests/crewai/test_crewai.py
bee-hive/tests/workflow/__init__.py
bee-hive/tests/workflow/pic.md
bee-hive/tests/workflow/test_sequence.py
test/examples/test_condition.py

* Updates imports to:
* Use . style within a module (ie within bee_hive)
* Use 'from bee_hive import XX' elsewhere (in tests, demos)
* Adds SPDX headers in .py files where not present 
Where necessary symbol exports were added in __init.py__
Tested:
* pytest, crewai agent, crewai workflow
* pip install & checked CLI runs
Caveat
* Only exported symbols *needed* by the above. This may be less than we expect consumers to need to actually use workflow. Or it may be more once the CLI is in place....

chore(internal): refactor imports

---

.github/workflows/check_schema.yaml
tools/ci/check-schemas.sh

Adds CI check for schema validation ([CLICK FOR EXAMPLE RUN](https://github.com/i-am-bee/bee-hive/actions/runs/13197461780))
Notes:
* we don't currently enforce tests pass via a branch protection rule - in fact we can't in a private repo
* Added as separate task to make it clear this is a different check (as we get set up)
* The crewai agent also uses a default name 'agents.yaml' for it's own agent definition! This will be renamed in a future PR
Partially addresses #178

feat(internal): Add schema check to ci

---

.github/workflows/maestro_demotest.yaml
maestro/demos/agents/crewai/activity_planner/activity_planner.py
maestro/demos/demos/activity-planner.ai/compose.yaml

POC of running a basic demo
- Runs the crewAI activity planner workflow (basic, does not use bee)
- Workflow launches Ollama only (not bee stack)
- Uses llama3.2:1b model 
- no checking of output
Based on results of this (after discussion) could consider
- Generalizing to search for demos matching certain criteria
- Adding bee-stack (this might require a custom action, use of a composite compose, or k8s, perhaps KinD)
- how to define expected results
Other tests are also possible that stub out external calls to ollama

feat(internal): Automated test of demo

---

maestro/schemas/workflow_schema.json
maestro/src/step.py
maestro/tests/yamls/workflows/input_workflow.yaml

fix #223 
Add `input` in the step.  It does:  
1. shows an input prompt and wait for user input
2.  generate the next prompt by replacing the `{prompt}` and `{response}`. in the template
An example of the input step is:
```
- name: input
input:
prompt: "Guess the number 1 through 6: "
template: Is the number {prompt} is same as {response}?  
```

Add input step

---

maestro/src/step.py

Previously in the input function, we are mapping the prompt after printing to the user, which means the printed  output would  dispaly the string literal {prompt}:
Response:
Here are the retrieved papers:
{prompt}
Select the papers you want to summarize by entering numbers (comma-separated):
I've changed the order slightly to allow the replacement to happen before displaying to user, so we see this instead:
Here are the retrieved papers:
["Observation of a zero-energy excitation mode in the open Dicke model", "Learning Smooth and Expressive Interatomic Potentials for Physical", "When Wyner and Ziv Met Bayes in Quantum-Classical Realm", "Real operator systems", "Universal quantum computation by interference of monochromatic", ]
Select the papers you want to summarize by entering the full …

fix display error for input

---

.github/workflows/maestro_demo-tests.yaml

@george-lhj let's make all demos the same. Changed it here but for future all demos should be run the same way (as much as possible) this is why I suggested in issue #244 that we create a `tools/run-demos.sh` that iterates over the `demos/workflows` and runs each demo in turn. This bash script can then be called from `.github/workflows/maestro_demo-tests.yaml`.
Thanks.

make CI running demos the same

---

maestro/deployments/Dockerfile
maestro/deployments/api.py
maestro/deployments/deployment.yaml
maestro/deployments/entrypoint.sh
maestro/deployments/maestro.html
maestro/deployments/maestro.sh
maestro/deployments/service.yaml
maestro/src/__init__.py
maestro/src/deploy.py

Add new `Deploy` class.
The constructor takes agent yaml, workflow yaml files and necessary runtime environment variables.
There are 2 deploy time environment variables. 
1. CONTAINER_CMD: command to build container image (docker, podman, nerdctl, ...) 
2. BUILD_FLAGS: flags necessary to build the container image (--namespace=k8s.io, ...
Here is an example
```
deploy = Deploy("../tests/examples/condition_agents.yaml", "../tests/examples/condition_workflow.yaml", "BEE_API_KEY=sk-proj-testkey BEE_API=http://192.168.86.45:4000")
```
It has 2 instance methods.
```
deploy.deploy_to_docker()
deploy_to_kubernetes()
```
After these method are executed, web interface is available at http/ <host address:port>/static/maestro.html
The host address and port are
Docker: 127.0.0.1:5000
Kubernetes: …

Add deploy class

---

maestro/schemas/workflow_schema.json
maestro/src/agent.py
maestro/src/bee_agent.py
maestro/src/crewai_agent.py
maestro/src/mock_agent.py
maestro/src/step.py
maestro/src/workflow.py
maestro/tests/bee/test_bee.py
maestro/tests/crewai/test_crewai.py
maestro/tests/examples/test_parallel.py
maestro/tests/yamls/agents/simple_agent.yaml
maestro/tests/yamls/workflows/parallel_workflow.yaml

Adding **parallel** in step.  The parallel has a list of agent.  The agents are executed in parallel and the step waits until the all agent complete.
Here is the sample workflow yaml file.
```yaml
kind: Workflow
metadata:
name: input_workflow
labels:
app: input
spec:
template:
metadata:
name: input_workflow
labels:
app: example
use-case: test
agents:
- test1
- test2
- test3
- test4
- test5
prompt: Select a number 1 through 6
exception: step4
steps:
- name: list
agent: test1
- name: parallel
parallel:
- test2
- test3
- test4
- name: result
agent: test5
```

Add parallel

---

maestro/src/deploy.py

Move the temp directory for the deploy to $(tempfile.gettempdir())"/maestro".  My Mac had "TMPDIR" defined.  It was the issue for my case.  
This is from the doc:
```
The directory named by the TMPDIR environment variable.
The directory named by the TEMP environment variable.
The directory named by the TMP environment variable.
A platform-specific location:
On Windows, the directories C:\TEMP, C:\TMP, \TEMP, and \TMP, in that order.
On all other platforms, the directories /tmp, /var/tmp, and /usr/tmp, in that order.
As a last resort, the current working directory.
```

fix temp directory

---

framework/bee-py/README.md
framework/bee-ts/README.md

Both the python and typescript frameworks can be found at: https://github.com/i-am-bee/beeai-framework

drop framework references

---

maestro/src/step.py

fixes #272 
Currently in the demo, the input keyword basically allows us to kind of "modify the prompt" a bit. In response to this, I've added an additional small feature, which is to pass a specific prompt using the {CONNECTOR} keyword to take advantage of this structure. 
Example usage in the meta agent demo:
agent1: creates the agent yamls necessary for a topic (in this case weather)
input: {CONNECTOR}.  /// because we don't want these files as output, but rather the prompt for the next agent2
agent: create the workflow yaml using what agents are being defined

add prompt passing feature

---

maestro/src/agents/meta_agent/README.md
maestro/src/agents/meta_agent/agents.yaml
maestro/src/agents/meta_agent/workflow.yaml

Previously was fixed for weather demo case, but now added another agent which would take in the user prompt for any case, and format it correctly no matter which demo.
Fixes #280, still need to do this for the workflow creation.

Generalizing agent creation within meta-agents

---

maestro/src/mermaid.py
maestro/src/workflow.py
maestro/tests/workflow/test_mermaid.py
maestro/tests/yamls/workflows/simple_workflow.yaml

Closes issue #290 
* implements `Workflow::to_mermaid`
* includes a new `Mermaid` class where all the code is
* includes both mermaid markdown for `sequenceDiagram` and `flowchart`
* includes tests
Only tested with `tests/yamsl/workflows/simple_workflow.yaml` but should work for the others. If not please open bug.
Also, does not include representation for `loop` or `condition` or `exception` or `on` events. I will address these in issue #297

first version of Workflow::to_mermaid method

---

maestro/tools/run-demos.sh

Fixes #329 
There are two separate issues with the run-demos.sh script:
Issue 1: Spaces in File Paths
When a user has spaces in their file path the script incorrectly splits these paths at spaces, treating each word as a separate directory. Fixed using the null-terminated output format of find with a proper while read loop to preserve spaces
Issue 2: Maestro Not Found
The script can't find the maestro command in certain environments
Fix: Add more robust checking and installation options:
Check if poetry is available
Try multiple ways to find maestro through poetry
Attempt to install via poetry if needed
Try this 
@maximilien

adding more poetry checks and space handling

---

maestro/schemas/workflow_schema.json
maestro/src/mermaid.py
maestro/tests/workflow/test_mermaid.py
maestro/tests/yamls/workflows/simple_cron_many_steps_workflow.yaml
maestro/tests/yamls/workflows/simple_cron_workflow.yaml

When merged this will complete the `event` subtask of issue #297 
Change highlights:
* changed workflow schema to use `event` instead of `on` which is reserved word for JSON/JavaScript (I think)
* changed `event` schema to take `name` and alternatively `agent` or `steps` for multi-steps event handling
* small refactor of `Workflow` class to add methods for fixing agent names and finding agent for a step
* added ``__to_sequenceDiagram_event to generate sequenceDiagram mermaid for event 
TODO: complete `__to_flowchart_event` to generate sequenceDiagram mermaid for event 
As example, for workflow YAML:
```yaml
apiVersion: maestro/v1
kind: Workflow
metadata:
name: simple cron workflow
labels:
app: cron-example    
spec:
template:
metadata:
name: cron-example
labels:
app: cron
use-case: test …
```

feature: adds mermaid for workflow events (cron)

---

maestro/deployments/api.py

closes #339 
Previous code is replacing \n with \ndata: (which is markdown line break + next data prefix), but it's putting it all in one yield, which causes multiple lines to be appended as one message

fixed newline error

---

maestro/src/mermaid.py
maestro/tests/workflow/test_mermaid.py

When merged this will solve parts of the `parallel` subtask of issue #297.
This PR includes the sequenceDiagram. So for a workflow as:
```yaml
apiVersion: maestro/v1
kind: Workflow
metadata:
name: input_workflow
labels:
app: input
spec:
template:
metadata:
name: input_workflow
labels:
app: example
use-case: test
agents:
- test1
- test2
- test3
- test4
- test5
prompt: Select a number 1 through 6
exception:
name: step4
agent: test4
steps:
- name: list
agent: test1
- name: parallel
parallel:
- test2
- test3
- test4
- name: result
agent: test5
```
This will generate mermaid:
```mermaid
sequenceDiagram
participant test1
participant test2
participant test3
participant test4
participant test5
test1->>test1: list
test1->>test5: parallel
par
test1->>test2: parallel
and
test1->>test3: parallel
and …
```

feature: adds parallel sequenceDiagram

---

maestro/src/mermaid.py
maestro/tests/workflow/test_mermaid.py

When merged this will solve the `parallel` subtask of issue #297.
This PR includes the sequenceDiagram. So for a workflow as:
```yaml
apiVersion: maestro/v1
kind: Workflow
metadata:
name: loop workflow
labels:
app: example
spec:
strategy:
type: sequence
template:
metadata:
name: loop-workflow
labels:
app: example
use-case: test
agents:
- generate1-10
- countdown
prompt: Generate a number
steps:
- name: step1
agent: generate1-10
- name: step2
loop: 
agent: countdown
until: (input.find("happy") != -1)
```
This will generate mermaid:
```mermaid
sequenceDiagram
participant generate1_10
participant countdown
generate1_10->>generate1_10: step1
generate1_10->>generate1_10: step2
loop (input.find("happy") != -1)
generate1_10-->countdown: until
end
```
I will work on generating flowchart as …

feature: Issue #297 loop sequenceDiagram

---

maestro/cli/commands.py
maestro/cli/maestro.py
maestro/deployments/api.py
maestro/tests/cli/test_commands.py

fixes #332 
added new --auto-prompt flag to the maestro deploy command. When present, the deployed Maestro UI will automatically start the workflow using the prompt specified in the YAML file.
By default upon load, we will need to wait for the user to enter the prompt if the flag is not added
Added --auto-prompt flag to maestro deploy CLI definition (maestro.py, commands.py)
Set AUTO_RUN=true as an environment variable if --auto-prompt is used
Updated api.py to conditionally run the workflow on page load if AUTO_RUN is set or a prompt is manually submitted
added test

fixing default prompt issue

---

maestro/demos/workflows/meta-agents/weather/agent/workflow.yaml
maestro/demos/workflows/meta-agents/weather/output/agents.yaml
maestro/demos/workflows/meta-agents/weather/output/workflow.yaml
maestro/demos/workflows/meta-agents/weather/workflow/workflow.yaml
maestro/demos/workflows/weather-checker.ai/agents.yaml
maestro/demos/workflows/weather-checker.ai/workflow.yaml

in preparation for demo, have renamed agents in weather demo, meta agents, and meta agents output so they reflect their usage better. Also, this is reflected in the creation of the mermaid graphs, as seen here:
closes #344

Agent renaming

---

maestro/src/agents/bee_agent.py

fixes #370 
The agent creation fails with a KeyError for "id" because the multi-line instructions (using a plain vertical bar) retained an extra newline. This extra newline caused the manually constructed JSON payload to be malformed, resulting in an unexpected response from the API.
Switched from manually building the JSON string using an f-string to constructing a Python dictionary and serializing it with json.dumps. This ensures all special characters and newlines in fields like "instructions" are properly escaped.
Optionally, applied .strip() to the instructions value to remove any unwanted leading/trailing whitespace.
Also changed the top_p (which is the probability distribtion param) to be 0.8 instead of 1; since we want more deterministic answers

Bug: using json serialization instead of fstrings to prevent newline errors

---

maestro/src/agents/bee_agent.py

fix #362 
This is for beeai agent only.  When the agent with the same name and model exists, the agent is used instead of creating a new one.

reuse existng agent

---

maestro/cli/commands.py
maestro/cli/maestro.py
maestro/cli/streamlit_deploy.py
maestro/cli/streamlit_meta_agents_deploy.py
maestro/cli/streamlit_workflow_ui.py
maestro/src/workflow.py
maestro/tests/cli/test_commands.py
maestro/tests/meta_agents/simple_prompt.txt

Still TODOs:
@george-lhj this is not fully ready but worth trying at least to test the meta-agents workflow for generating the agents. You can try it with:
```bash
./maestro meta-agents tests/meta_agents/simple_prompt.txt
```
OR change ` tests/meta_agents/simple_prompt.txt` to a different file. If file does not exist it should default to a simple prompt.
When complete and merged this will close issue #365

feature: first version of meta-agents streamlit UI/UX

---

maestro/demos/workflows/meta-agents/activity-planner.ai/agents/agents.yaml
maestro/demos/workflows/meta-agents/activity-planner.ai/agents/workflow.yaml
maestro/demos/workflows/meta-agents/activity-planner.ai/workflow/agents.yaml
maestro/demos/workflows/meta-agents/activity-planner.ai/workflow/workflow.yaml
maestro/src/agents/meta_agent/agents.yaml
maestro/src/agents/meta_agent/workflow_agent.yaml
maestro/src/agents/meta_agent/workflow_workflow.yaml
maestro/tests/meta_agents/weather_prompt.txt

Added a formatting agent so that the yaml output on the deploy looks more readable.
Heres what it looks like:

added Markdown formatter in prep for demo

---

maestro/demos/workflows/meta-agents/activity-planner.ai/agents/agents.yaml
maestro/demos/workflows/meta-agents/activity-planner.ai/agents/workflow.yaml
maestro/demos/workflows/meta-agents/activity-planner.ai/workflow/agents.yaml
maestro/demos/workflows/meta-agents/activity-planner.ai/workflow/workflow.yaml
maestro/src/agents/meta_agent/agents.yaml
maestro/src/agents/meta_agent/workflow_agent.yaml
maestro/src/agents/meta_agent/workflow_workflow.yaml

fixes #394 
add an agent to takes in the final yaml format of the output, and then adds tags
<file start>
content
</file>
so that we can parse the content and directly upload
here is what output looks like:

Add parsers

---

maestro/cli/streamlit_meta_agents_deploy.py
maestro/cli/streamlit_workflow_ui.py

Fix #395 
This PR adds "Load generated files" button in the "Generated" tab.  This expects the generated file names are 
```
generated_agent = "generated_agent"
generated_workflow = "generated_workflow"
```
in the working directory.

feature: load and create generated <agents/workflow>.yaml files

---

maestro/cli/commands.py
maestro/cli/common.py
maestro/cli/maestro.py
maestro/tests/cli/test_commands.py

This PR solves issue #306 by adding `--prompt` for run commands:
```bash
maestro git:(main) ./maestro run ./tests/yamls/agents/simple_agent.yaml ./tests/yamls/workflows/simple_workflow.yaml --prompt --verbose --dry-run
Enter your prompt: lol
Mock agent:Loading code_interpreter
[...]
🤖 Response from test3: lol
```

fixes issue #306 by adding --prompt to run command

---

maestro/demos/workflows/weather-checker.ai/agents.yaml

Weather checker prompt doesn't perform super consistently, so giving an example process allows it to act faster and more accurate.

enhancement: prompt adjustment

---

maestro/demos/README.md
maestro/demos/workflows/summary.ai/README.md
maestro/demos/workflows/summary.ai/agents.yaml
maestro/demos/workflows/summary.ai/workflow.yaml

fully redesigned summary ai using agents in order to support the following client needs:
1) Know when new IBM papers hit the ArXiv
2) Search ArXiv for papers on a certain topic during a certain time period (only for IBM documents)
3) Retreive metadata, create summary for certain paper
4) Send the summary to your slack
future updates:
1A) Look into creating own tool in python that can create better summary from PDF
1B) Currently only output of first agent is something like this ['title1','title2', etc]. Currently the rest of the agents only can handle one title at a time, but I need support for a loop or parallel with each title in output @akihikokuroda 
...
2) Support for non ibm docs? (could be a lot slower because the freuqency of released docs are much higher)

demo: new summary demo to align w/clients needs

---

demos/README.md
pyproject.toml
src/agents/agent_factory.py
src/agents/custom_agent.py
src/agents/metrics_agent.py
tests/agents/test_metrics_agent.py
tests/yamls/agents/metric_agent.yaml
tests/yamls/workflows/metric_workflow.yaml

For LLM evaluation, user want to rank/determine the best performing responses. OPIK is open source and does it, but makes calls from openai by default. As a workaround i have added support in the src file for this agent to point it at the ollama backend that we are running.

feature: adding metric evaluation agent using opik

---

demos/README.md
demos/workflows/mcp-gh-tools.ai/README.md
demos/workflows/mcp-gh-tools.ai/agents.yaml
demos/workflows/mcp-gh-tools.ai/workflow.yaml
demos/workflows/openai-mcp.ai/README.md
demos/workflows/openai-mcp.ai/agents.yaml
demos/workflows/openai-mcp.ai/workflow.yaml

I’m trying to reproduce the “Who am I?” flow in a demo with calling the Github MCP tool, but I keep hitting “tools not found” errors. I realize I may not fully understand how Maestro wires up function calls to the MCP server, so hope you can take a look at my workflow configuration/prompts to see my flaw in logic.
What I’ve done so far:
Pointed MAESTRO_MCP_ENDPOINTS at my local github-mcp-server stdio.
Switched my agent to mode: local so it can spawn the MCP server.
In my prompt, I’ve asked the model to "GH MCP tools in order to fetch relevant information”
Where I’m getting stuck:
LLM will end up choosing some functions/tools to use, but doesn't seem like they are able to be exectued
I’m not sure whether I need a tools: declaration in agents.yaml, or a special function_call setting, or …

demo: mcp setup

---

src/workflow.py
tests/workflow/test_inputs.py
tests/yamls/agents/dry_run_inputs_agent.yaml
tests/yamls/workflows/dry_run_inputs_workflow.yaml

fix #500 
This PR enables a new input type: pulling an agent’s instructions field from a previous step (e.g., for reflection, reuse, meta-programming, etc.).

enhance step/inputs

---

demos/workflows/cbom.ai/README.md
demos/workflows/cbom.ai/agents.yaml
demos/workflows/cbom.ai/workflow.yaml
demos/workflows/cbom.ai/workflowrun.yaml

fixes #511, reduces time from 5 min to <1 sec for the initial agent.
@akihikokuroda am i correct in assuming since this agent is now a code agent, it should not be included in the `workflowrun.yaml` file? Since the other code agents are also not included?

demo: change fetch tool from llm to codeagent

---

README.md

`maestro run <agent_path>` is an invalid command
also we're using apache not mit license

fix broken agent command in readme

---

src/maestro/agents/openai_agent.py
src/maestro/cli/fastapi_serve.py

Updates `maestro serve` to support a configurable env var `CORS_ALLOW_ORIGINS` for CORS. This comma-delimitated var is read from the env at the startup of maestro serve, and by default is empty

fix: allow cors for maestro serve

---

.github/workflows/maestro_check-mermaid.yaml
.github/workflows/maestro_check-schemas.yaml
.github/workflows/maestro_demo-tests.yaml
.github/workflows/maestro_deploy-tests.yaml
.github/workflows/maestro_operator-build.yaml
.github/workflows/maestro_operator-test.yaml
.github/workflows/maestro_release.yaml
.github/workflows/maestro_run-tests.yaml
CONTRIBUTING.md
README.md
demos/CONTRIBUTING.md
demos/agents/crewai/activity_planner/README.md
demos/workflows/activity-planner-crewai.ai/README.md
demos/workflows/common/doctor.sh
pyproject.toml
src/maestro/agents/meta_agent/doctor.sh
tools/run-demos.sh

Fixes #592 (See there for the reasoning)
Replaces `uv pip install -e .` with `uv sync` in the docs, scripts and CI.
Also fixes a bug in `pyproject.toml` that only surfaces when using `uv sync` and not `uv pip install -e .` or `uv build`

chore: switch to `uv sync` for dev install

---

.release_names.md

strikethough the name we used to script can use it next time. This is already implemented in our script, but this version was done manually.

chore: update release_names.md to match name

---

.github/workflows/maestro_build_upload_images.yaml
.github/workflows/maestro_release.yaml
Dockerfile
pyproject.toml

permission has to be granted individually to any job based on how it uses `secrets.GITHUB_TOKEN`, by default only `read` is allowed on orgs but for users it's `write`
This extended #642 to also allow write for opening a PR and package write for the docker image CI
I also reverted back to `0.3.0` so we can do a fresh `v0.3.0` release rather than a patch

bug: set correct CI perms for releases

---

.github/workflows/maestro_release.yaml

As seen in the latest release CI https://github.com/AI4quantum/maestro/actions/runs/16351669752/job/46200013327#step:5:149
creating PRs requires a separate permissions config than creating a branch, due to this bug I had to manually open #644

bug: release ci need separate pr write perms

---

operator/Dockerfile-engine
pyproject.toml
tests/agents/crewai_agent/test_crewai.py

Remove crewai optional dependency from pyproject.toml.  It is causing a conflict with beeai-framework.
#650 left open to fix or clean up the CrewAI agent.

bug: remove crewai agent 

---

pyproject.toml

Fixes #662
See the error when running uv sync on CI in maestro demos
https://github.com/AI4quantum/maestro-demos/actions/runs/16503394356/job/46667742064?pr=12
```
[stderr]
/home/runner/work/_temp/setup-uv-cache/builds-v0/.tmpIYgb8l/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82:
SetuptoolsDeprecationWarning: `project.license` as a TOML table is
deprecated
!!
```
Updated guidelines [here](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license)

project license as a toml table is deprecated

---

src/maestro/agents/beeai_agent.py
src/maestro/agents/openai_agent.py
tests/yamls/agents/funnier_local_agents.yaml
tests/yamls/agents/simple_local_agent.yaml

Fixes #657 
This removes the reliance on env vars for beeai and openai agents by allowing the config of the api url via the yaml and not just the env var and setting a dummy key by default if the api key env var is not set.

feat: enable llm url override via yaml spec

---

pyproject.toml
src/maestro/cli/commands.py
src/maestro/schemas/agent_schema.json
src/maestro/schemas/tool_schema.json
src/maestro/schemas/tool_toolhive_schema_full.json
src/maestro/schemas/workflow_schema.json
tests/cli/test_commands.py
tests/integration/dry_run/test_dry_run.py

fixes #665 
moved scehmas into package resources so we can bundle them in pyproject and allow maestro validate to work outside of repo.

enhancement/bug: allow validate to be accessible outside of repo

---

.github/workflows/maestro_run-tests.yaml
src/maestro/deploy.py
tests/cli/test_commands.py

While tracking down an error in #675 we found that the pytest failures summary isn't shown in the CI, this updates the CI to show the results summary.
In addition, while forging out how to display the summary I noticed that three test that leverage the `deployments/Dockerfile` were silently failing. I updated the code so the failures are no longer silent, but then added a pytest skip (as was used by the other deploy tests). I will open a separate follow up issue to get the deploy tests passing (as fixing the Dockerfile was non-trivial)

test: improve test output in CI

---

.github/workflows/maestro_build_upload_images.yaml

While working on adding a docker image publishing CI on maestro-knowledge I noticed there was a significant typo in our release ci. Due to this, the current `maestro-cli` image is actually just a copy of the `maestro` image. This will fix this in the next release

fix: maestro-cli docker image was mistagged

---

src/maestro/agents/agent.py

fix #696 
The output is like:
```
🐝 08-15-2025 12:15:36: Running read-a-file...
```

feat: add timestamp to agent messages

---

docs/USER_GUIDE.md
src/maestro/mcptool.py
src/maestro/tool_utils.py
tests/test_tool_utils.py

fix #698 
MCP servers can be registered by a file that is specified by "MCP_SERVER_LIST" environment variable.
The file is in json format and it has list of MCP servers.
Each MCP server  has "name", "url", "transport" and "access_token"
Example of the file:
```
[                                                                                                                                                       
{                                                                                                                                                   
"name": "slack",                                                                                                                                
"url": "http://localhost:30055", …
```

feat: local mcp server registration

---

src/maestro/agents/query_agent.py
tests/agents/test_query_agent.py

https://github.com/AI4quantum/maestro-knowledge/pull/65 updated the `search` tool in maestro-knowledge to return a string instead of a dict for more consistent tool response types. Previously the tool would return a dict if valid or an error string if not. The query agent would check if it's a string and assume it's an error (which caused all queries to return an error).
This updates the result handling to instead use `json.loads` to parse the result for the expected dict and handles a `json.JSONDecodeError` if the result is an error string.

fix: update query agent to match latest maestro-knowledge api changes

---

src/maestro/agents/dspy_agent.py

fix #744 
If the llm is not available, this message comes out.
```
% uv run maestro run tests/yamls/agents/dspy_agent.yaml tests/yamls/workflows/dspy_workflow.yaml
🔍 [DEFAULT ROUTING] Step 'step1' using previous step output:
Prompt: Where is the next Olympics game location?
💭 10-02-2025 14:29:01: Running Dspy agent: DSPyAgent with prompt: Where is the next Olympics game location?
/Users/akihikokuroda/development/repositories/AI4quantum/maestro/.venv/lib/python3.12/site-packages/httpx/_models.py:408: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.
headers, stream = encode_request(
No response from Agent
```

enhancement: dspy agent fix error handling
